### ISSUE TITLE
Not rendering styles but deleting them

### ISSUE THREAD

**Issue by luisjmontoro** [tbrasington/text-to-styles#9]
Hello!

I'm a big fan of this plugin, which I've been using a lot the past months to help clean many design libraries.

Lately, the plugin is not rendering any text styles as it use to. When I run the plugin it says that 0 styles have been rendered and also deletes the local styles that the document already had. I've tried reinstalling the plugin several times and running the plugin on different Sketch files but it keeps failing. Currently I'm using Sketch v59.1, I don't know if it would have anything to do with the issue. 

Thanks! :)

**Comment by tbrasington** [comment]
Hi @luisjmontoro thank you, glad it has been helpful. 

Do you have a sample file I can debug please?

**Comment by luisjmontoro** [comment]
Hello, it does it on any Sketch file. I've created one and tested it and it keeps failing. 
[example-to-debug.sketch.zip](https://github.com/tbrasington/text-to-styles/files/3875406/example-to-debug.sketch.zip)
Please, let me know if I can send you more details.
Thanks!

**Comment by tbrasington** [comment]
Hi @luisjmontoro just to check that your document has the Pages set up with the Styles, Colors and Alignments? The sample file doesn't which is why it won't do anything.

This is what it should look like: [Sketch file](https://www.amazon.co.uk/clouddrive/share/XJ9wP0hwCGxnZ6j32UI32g1ndlTB6wwJTNXpgLZHmVB)
![screenshot of sketch](https://content-eu.drive.amazonaws.com/cdproxy/templink/f1Hs0CjyYyHAYvrSpdiujkGLoE-Wcf0Ao53g6Lrpz_oeJxFPc?viewBox=1195%2C722&ownerId=A2JL10XOR72YUA)

**Comment by luisjmontoro** [comment]
Thanks @tbrasington! Truth is I've never had those pages created and I've been using the plugin successfully until a couple of weeks. The plugin automatically generated a new page when running it called 'Rendered styles' with all the text styles of both document and library.

**Comment by tbrasington** [comment]
That is mysterious. But it raises a few features I need to develop. 

Is everything working for you now?

**Comment by tbrasington** [comment]
Version 4.0.0 will now show a message if a Page is missing. there is also a first run feature.
